CREATE TABLE IF NOT EXISTS PRODUCT(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)VALUES
("A1","Chocolate","1","1","10 boxes",15),
("B1","Toffee","1","2","10 packets",20),
("C1","Tea powder","2","1","10 packets",18),
("D1","Hot Sauce","2","2","10 bottles",15.5),
("E1","Chilli powder","2","1","10 packets",23.47);
SELECT * FROM PRODUCT
SELECT COUNT(PRODUCT_ID) AS MYPRODUCTCOUNT FROM PRODUCT;
SELECT AVG(PRICE) AS Average_Price FROM PRODUCT;
SELECT SUM(PRICE) AS Total_Price FROM PRODUCT;